### ISSUE TITLE
[Bug]: Cannot print out logo or address on receipt

### ISSUE THREAD

**Issue by hrkyip** [caterlord/MobilePos-feedback#22]
### Platform

Android

### App build number

1.2.15

### Issue summary

After setting up store address and logo on HQ, it did not reflect on POS.

### Steps to reproduce

1. Go to set up logo and address in HQ.
2. Go back to POS and create receipt.

### Expected behavior

Logo and address should be displayed on receipt.

### Actual behavior

Nothing come out.

### Screenshots or logs

<img width="807" height="440" alt="Image" src="https://github.com/user-attachments/assets/b0b8bac7-d8c9-4988-859b-16440677f0d3" />

<img width="1597" height="308" alt="Image" src="https://github.com/user-attachments/assets/b08ba655-ba4b-4c1b-88a0-e2ce75810815" />

![Image](https://github.com/user-attachments/assets/7cd7c53e-fb87-4300-9377-11b72701e528)

**Comment by bearyung** [comment]
Hi @hrkyip,

Thank you for the detailed report. We're now working on adding the shop name, address, and footer information to the receipt printout.

**What's being implemented:**
- Shop name (header section)
- Contact information (address, phone, email, etc.)
- Footer messages (thank you messages, promotional text)

**Note:** Logo printing requires embedding the image directly into the printer's ROM using the printer's configuration tools, so that part is not supported directly from the app.

Fix in progress on branch `feature/issue-22-receipt-shop-info`. We'll update this thread once the fix is available.

Internal tracking: caterlord/MobilePos#133

**Comment by bearyung** [comment]
Update: The fix has been implemented and a pull request has been created.

**What's included in the fix:**
- Shop name now appears prominently at the top of the receipt (larger, bold, centered text)
- Contact information (address, phone, email, etc.) displays below the shop name
- Footer messages appear at the bottom of the receipt

All fields support multi-line content if you've entered line breaks in HQ.

**Pull Request:** caterlord/MobilePos#134

The fix is pending review and will be included in an upcoming release. We'll update this thread once the fix is available.

**Comment by hrkyip** [comment]
Still cannot see the shop name on the receipt, and the address occupied the shop name space too.

<img width="382" height="514" alt="Image" src="https://github.com/user-attachments/assets/8080fed3-e3b4-4f8d-bb1e-8c1a424588ff" />
